### 课程管理
### 列表
POST {{content_host}}/content/course/list?pageNo=1&pageSize=10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3MTAwNjIyMTYsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjZlMjYzZmM4LTIxYmMtNGJlYy1hM2IzLTA4NDRlZjgzNTBmYiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.d62vafHTQroEta8bmwS5USWRXXn-K3S0L3wqskTv9bs
Content-Type: application/json

{
  "auditStatus": "202004",
  "publishStatus": "203001",
  "courseName": "java"
}

### 创建课程
POST {{gateway_host}}/content/course
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIlwiLFwidXNlcm5hbWVcIjpcInQxXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTcxMDE3Mjk1NywiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiI5MzNkYWIzOC01YzhlLTRkMDQtOWEzMi1kN2JlMzBlZDA4OGUiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.QCD0fMSy3JOWYmSVFCjVnrK8ntAWig7uLt6Qbq1XSGk
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "初级人员",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员初级人员初级人员",
  "tags": "",
  "grade": "204001",
  "description": ""
}

### 课程查询列表
POST {{gateway_host}}/content/course/list?pageNo=2&pageSize=1
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}

### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=t1&password=111111
